name: Build Snake Game on Multiple Platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libncurses5-dev

    - name: Build with Makefile on Linux
      if: matrix.os == 'ubuntu-latest'
      run: make

    - name: Archive the compiled game
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: snake-game-linux
        path: ./snake

    - name: Clean up
      if: matrix.os == 'ubuntu-latest'
      run: make clean
